name: "Last successful commit"
description: "Get the commit hash of the last successful workflow run on a given branch"
inputs:
  branch: # branch to analyze
    description: "Branch to get last successful commit from"
    required: false
  github_token: # github token to use
    description: "Your GitHub access token"
    required: true
  workflow_id: # ID or filename of the workflow
    description: "ID or filename of the workflow"
    required: true
  event: # Event that triggers workflow
    description: "Event that triggers workflow"
    required: false

outputs:
  commit_hash: # hash of the last successful workflow run
    description: "Last successful commit"
runs:
  using: "node12"
  main: "dist/index.js"
